apiVersion: v1
kind: ServiceAccount
metadata:
  name: subject1
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: subject2
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: subject3
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: subject4
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role1
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role2
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role3
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role1-to-subject1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role1
subjects:
  - kind: User
    name: subject1
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role2-to-subject2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role2
subjects:
  - kind: User
    name: subject2
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role3tosubject3and4
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role1
subjects:
  - kind: User
    name: subject3
    namespace: default
  - kind: User
    name: subject4
    namespace: default
